---

- name: IBM InfoSphere Information Server
  hosts: all
  any_errors_fatal: true
  roles:
    - IBM.infosvr

  pre_tasks:
    - name: ensure group_vars location exists
      file:
        path: /root/playbooks/group_vars
        state: directory
    - name: copy vars into group_vars
      copy:
        src: /mnt/media/vars.yml
        dest: /root/playbooks/group_vars/all.yml
