---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

- name: patch - copy {{ ibm_infosvr_patch_definition.srcFile }}
  copy:
    src: "{{ ibm_infosvr_media_dir }}/{{ ibm_infosvr_patch_definition.srcFile }}"
    dest: "{{ ibm_infosvr_install_location.linux }}/Updates/Downloads/{{ ibm_infosvr_patch_definition.srcFile }}"
    force: no

- name: patch - extract {{ ibm_infosvr_patch_definition.srcFile }}
  unarchive:
    src: "{{ ibm_infosvr_install_location.linux }}/Updates/Downloads/{{ ibm_infosvr_patch_definition.srcFile }}"
    dest: "{{ ibm_infosvr_install_location.linux }}/Updates/Downloads"
    creates: "{{ ibm_infosvr_install_location.linux }}/Updates/Downloads/{{ ibm_infosvr_patch_definition.pkgFile }}"
    copy: no

- name: patch - install {{ ibm_infosvr_patch_definition.srcFile }}
  shell: >
          umask 022 &&
          {{ ibm_infosvr_install_location.linux }}/Updates/bin/installUpdates
          -installLocation {{ ibm_infosvr_install_location.linux }}
          -patchPackage {{ ibm_infosvr_install_location.linux }}/Updates/Downloads/{{ ibm_infosvr_patch_definition.pkgFile }}
          -user {{ ibm_infosvr_user_isadmin }}
          -password {{ ibm_infosvr_upwd_isadmin }}
          -console
          -wasadmin {{ ibm_infosvr_user_was }}
          -waspassword {{ ibm_infosvr_upwd_was }}
          -acceptlicense
          -dbadmin {{ ibm_infosvr_user_db2_instance }}
          -dbpassword {{ ibm_infosvr_upwd_db2_instance }}
          {% if ibm_infosvr_force.patch is defined and ibm_infosvr_force.patch %}-force{% endif %}
  register: __ibm_infosvr_patch_install
  when: >
    __ibm_infosvr_patching_file.stat.exists
    and ibm_infosvr_version_xml.find(ibm_infosvr_patch_definition.versionId) == -1

- name: patch - clean up installation files
  file: path={{ item.file }} state={{ item.state }}
  with_items:
    - { file: "{{ ibm_infosvr_install_location.linux }}/Updates/Backup.*", state: 'absent' }
    - { file: "{{ ibm_infosvr_install_location.linux }}/Updates/Downloads/*.zip", state: 'absent' }
    - { file: "{{ ibm_infosvr_install_location.linux }}/Updates/Downloads/*.tar", state: 'absent' }
    - { file: "{{ ibm_infosvr_install_location.linux }}/Updates/Downloads/*.tar.gz", state: 'absent' }
  become_user: root
  become: yes

- import_tasks: ops/stop_engine.yml
  when: >
          __ibm_infosvr_patch_install is changed
          and ('ibm_information_server_engine' in group_names)

- import_tasks: ops/stop_domain.yml
  when: >
          __ibm_infosvr_patch_install is changed
          and ('ibm_information_server_domain' in group_names)

- import_tasks: ops/stop_sos.yml
  when: >
          __ibm_infosvr_patch_install is changed
          and ('ibm_information_server_domain' in group_names)

- import_tasks: ops/regen_sos.yml
  when: >
          __ibm_infosvr_patch_install is changed
          and ('ibm_information_server_domain' in group_names)

- import_tasks: ops/start_sos.yml
  when: >
          __ibm_infosvr_patch_install is changed
          and ('ibm_information_server_domain' in group_names)

- import_tasks: ops/start_domain.yml
  when: >
          __ibm_infosvr_patch_install is changed
          and ('ibm_information_server_domain' in group_names)

- import_tasks: ops/start_engine.yml
  when: >
          __ibm_infosvr_patch_install is changed
          and ('ibm_information_server_engine' in group_names)
