---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

- name: db2client - check install location exists
  stat:
    path: "{{ ibm_infosvr_tmp.linux }}/is-suite"
  changed_when: False
  register: __ibm_infosvr_db2client_tmp

- name: db2client - apply DB2 client response file template
  template: src={{ item.file }} dest={{ item.target }} owner=root group=root mode=0644
  with_items:
    - { file: 'db2client.j2', target: "{{ ibm_infosvr_tmp.linux }}/is-suite/db2client.rsp" }
  when: not ('ibm_information_server_external_db' in group_names) and __ibm_infosvr_db2client_tmp.stat.exists

- name: db2client - install DB2 client
  command: >
          {{ ibm_infosvr_tmp.linux }}/is-suite/payloads/Shared/DB2/payload/db2setup
          -r {{ ibm_infosvr_tmp.linux }}/is-suite/db2client.rsp
  args:
    creates: "{{ ibm_infosvr_install_location.db2 }}/bin/db2"
  when: not ('ibm_information_server_external_db' in group_names) and __ibm_infosvr_db2client_tmp.stat.exists
