---
- hosts: all
  become: yes
  tasks:
  - name: install apache2 server
    yum:
      name: httpd
      state: latest
  - name: starts the service
    service:
      name: httpd
      enabled: yes
      state: started
  - name: copy artifacts to tomcat
    copy:
      src: bahmni.omod
      dest: /var/www/bahmni.omod


