---
- hosts: all
  become: true
  vars:
    tomcat_version: 8.5.5
    
    tomcat_permissions_production: True
    
    tomcat_users:
      - username: "tomcat"
        password: "t3mpp@ssw0rd"
        roles: "tomcat,admin,manager,manager-gui"
      - username: "admin"
        password: "admin"
        roles: "tomcat"        
  roles:
    - role: zaxos.tomcat-ansible-role
  tasks:
  - name: copy war file into webapps
    copy: 
      src: /var/lib/jenkins/workspace/rafi-spring-pipe-night bulid/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar	
      dest: /var/lib/tomcat/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar

