---
- hosts: all
  become: true
  vars:
    tomcat_version: 8.5.5
    
    tomcat_permissions_production: True
    
    tomcat_users:
      - username: "tomcat"
        password: "t3mpp@ssw0rd"
        roles: "tomcat,admin,manager,manager-gui"
      - username: "admin"
        password: "admin"
        roles: "tomcat"        
  roles:
    - role: zaxos.tomcat-ansible-role
  tasks:
  - name: copy artifacts to tomcat
    copy:
      src: open.war
      dest: /opt/tomcat/webapps/open.war




   # get_url:
    #  url: https://s3-artifacts-manasa.s3.amazonaws.com/gameoflife-web/target/gameoflife.war
     # dest: /opt/tomcat/webapps/gameoflife.war
      
