---
- hosts: all
  become: true
  vars:
    tomcat_version: 8.5.5
    
    tomcat_permissions_production: True
    
    tomcat_users:
      - username: "tomcat"
        password: "t3mpp@ssw0rd"
        roles: "tomcat,admin,manager,manager-gui"
      - username: "admin"
        password: "admin"
        roles: "tomcat"        
  roles:
    - role: zaxos.tomcat-ansible-role
  tasks:
  - name: copy artifacts to tomcat
    get_url:
      url: http://3.135.217.36:8081/artifactory/maven/com/wakaleo/gameoflife/gameoflife-build/1.0-SNAPSHOT/gameoflife-build-1.0-20191130.150003-1.jar
      dest: /opt/tomcat/webapps/gameoflife.war
      url_username: admin
      url_password: password
  - name: Touch the same file, but add/remove some permissions
    file:
      path: /opt/tomcat/webapps/gameoflife.war
      state: touch
      mode: u+rw,g-wx,o-rwx
      
