---
- hosts: all
  become: true
  vars:
    tomcat_version: 8.5.5
    
    tomcat_permissions_production: True
    
    tomcat_users:
      - username: "tomcat"
        password: "t3mpp@ssw0rd"
        roles: "tomcat,admin,manager,manager-gui"
      - username: "admin"
        password: "admin"
        roles: "tomcat"        
  roles:
    - role: zaxos.tomcat-ansible-role
  tasks:
  - name: copy artifacts to tomcat
    get_url:
      url: http://3.136.26.232:8081/artifactory/webapp/#/search/quick/eyJzZWFyY2giOiJxdWljayIsInF1ZXJ5IjoiZ2FtZSJ9
      dest: /opt/tomcat/webapps/gameoflife-1.0-20191130.150003-1.pom
