---
- hosts: all
  become: true
  vars:
    tomcat_version: 8.5.5
    
    tomcat_permissions_production: True
    
    tomcat_users:
      - username: "tomcat"
        password: "t3mpp@ssw0rd"
        roles: "tomcat,admin,manager,manager-gui"
      - username: "admin"
        password: "admin"
        roles: "tomcat"        
  roles:
    - role: zaxos.tomcat-ansible-role
  tasks:
  - name: copy artifacts to tomcat
    get_url:
      url: http://18.222.106.39:8081/artifactory/maven/com/wakaleo/gameoflife/gameoflife-web/1.0-SNAPSHOT/gameoflife-web-1.0-20191130.150003-1.war
      dest: /opt/tomcat/webapps/gameoflife.war
