---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

- name: check status of Information Server services
  command: /usr/sbin/ss -tln -H
  register: __ibm_infosvr_status
  changed_when: False
  when: ('ibm_information_server_clients' not in group_names)

- name: check status of repository tier
  assert:
    that:
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.db2 | string) + ' ') > 0"
    msg: "Repository tier is not fully operational."
  when: ('ibm_information_server_repo' in group_names or 'ibm_information_server_external_db' in group_names)

- name: check status of domain tier
  assert:
    that:
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.console | string) + ' ') > 0"
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.default | string) + ' ') > 0"
    msg: "Domain tier is not fully operational."
  when: ('ibm_information_server_domain' in group_names)

- name: check status of WAS ND
  assert:
    that:
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.admin | string) + ' ') > 0"
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.secure_admin | string) + ' ') > 0"
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.bootstrap | string) + ' ') > 0"
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.ipc_connector | string) + ' ') > 0"
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.mutual_auth_listener | string) + ' ') > 0"
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.orb_listener | string) + ' ') > 0"
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.server_auth_listener | string) + ' ') > 0"
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.soap_connector | string) + ' ') > 0"
    msg: "Domain tier WAS ND is not fully operational."
  when: >
    ('ibm_information_server_domain' in group_names)
    and (not __ibm_infosvr_features.wlp)

- name: check status of open source services (domain)
  assert:
    that:
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.zookeeper | string) + ' ') > 0"
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.solr | string) + ' ') > 0"
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.kafka | string) + ' ') > 0"
    msg: "Shared open source services are not fully operational."
  when: >
          ('ibm_information_server_domain' in group_names)
          and not __ibm_infosvr_features.ises

- name: check status of open source services (ISES)
  assert:
    that:
      - "__ibm_infosvr_status.stdout.find(':2181 ') > 0"
      - "__ibm_infosvr_status.stdout.find(':9092 ') > 0"
    msg: "Shared open source services are not fully operational."
  when: >
          ('ibm_information_server_ug' in group_names)
          and __ibm_infosvr_features.ises

- name: check status of engine tier
  assert:
    that:
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.dsrpc | string) + ' ') > 0"
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.isf_agent | string) + ' ') > 0"
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.isf_agent_object | string) + ' ') > 0"
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.jobmon_port1 | string) + ' ') > 0"
      - "__ibm_infosvr_status.stdout.find(':' + (ibm_infosvr_ports.jobmon_port2 | string) + ' ') > 0"
    msg: "Engine tier is not fully operational."
  when: ('ibm_information_server_engine' in group_names)
