---
###
# Copyright 2018 IBM Corp. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

##########
# POST-INSTALL CONFIG

- name: configure - check existence of solr collection
  uri:
    url: "http://{{ ibm_infosvr_hosts.domain }}:58983/solr/admin/collections?action=list"
    method: GET
    status_code: 200
    validate_certs: no
    timeout: 120
    return_content: yes
  ignore_errors: yes
  register: __ibm_infosvr_solr_collections
  when: ('ibm_information_server_domain' in group_names)

- name: configure - configure solr for Information Analyzer (linux) (v11.5)
  shell: >
    export JAVA_HOME={{ ibm_infosvr_install_location.linux }}/jdk/jre &&
    ./solr create_collection
    -c da-datasets
    -shards 1
    -replicationFactor 1
    -port 58983
    -d {{ ibm_infosvr_install_location.linux }}/ASBServer/solr_configs/da_datasets_configs
  args:
    chdir: "{{ ibm_infosvr_install_location.linux }}/shared-open-source/solr/install/bin"
  become_user: root
  become: yes
  when: >
    ('ibm_information_server_domain' in group_names)
    and (__ibm_infosvr_version == "11.5")
    and (__ibm_infosvr_solr_collections.content.find('da-datasets') == -1)

- name: configure - update Solr indices
  uri:
    url: "https://{{ ibm_infosvr_hosts.domain }}:{{ ibm_infosvr_ports.console }}\
          /ibm/iis/dq/da/rest/v1/reindex?batchSize=25&solrBatchSize=100&upgrade=true&force=true"
    method: GET
    user: "{{ ibm_infosvr_user_isadmin }}"
    password: "{{ ibm_infosvr_upwd_isadmin }}"
    force_basic_auth: yes
    status_code: 200
    validate_certs: no
    timeout: 120
  ignore_errors: yes
  when: ('ibm_information_server_domain' in group_names)

- name: configure - ensure local cache directory exists
  file:
    path: cache/
    state: directory
  become: no
  delegate_to: localhost

- name: configure - apply WLM config template
  template:
    src: wlmconfig.json.j2
    dest: cache/wlmconfig.json
  become: no
  delegate_to: localhost
  when: ('ibm_information_server_domain' in group_names)

- name: configure - set WLM properties according to environment scale
  uri:
    url: "https://{{ ibm_infosvr_hosts.domain }}:{{ ibm_infosvr_ports.console }}\
          /ibm/iis/ds/api/engines/{{ hostvars[ibm_infosvr_hosts.engine].ansible_fqdn | upper }}/wlmconfig"
    method: POST
    user: "{{ ibm_infosvr_user_isadmin }}"
    password: "{{ ibm_infosvr_upwd_isadmin }}"
    body: "{{ lookup('file', 'cache/wlmconfig.json') }}"
    body_format: json
    force_basic_auth: yes
    status_code: 200
    validate_certs: no
    timeout: 10
    headers:
      Content-Type: "application/json; charset=utf-8"
  when: ('ibm_information_server_domain' in group_names)

- import_tasks: configure/configure-ia.yml
  become_user: root
  become: yes
  when: __ibm_infosvr_features.ia

# TODO: currently only enables masking for default 'dstage1' project
# -- should take a variable giving a list of projects
- import_tasks: configure/configure-odpp.yml
  when: __ibm_infosvr_features.masking

- import_tasks: configure/configure-em.yml
  become_user: root
  become: yes
  when: __ibm_infosvr_features.event_mgmt

- import_tasks: configure/configure-igd.yml
  become_user: root
  become: yes
  when: __ibm_infosvr_features.igd

- import_tasks: configure/configure-ug.yml
  become: yes
  when: >
          __ibm_infosvr_features.ises
          and __ibm_infosvr_version == "11.7"

- name: batch sync the ISES graph
  shell: >
    source ~/.bashrc &&
    source dsenv &&
    {{ ibm_infosvr_install_location.linux }}/Clients/istools/cli/istool.sh
    graph batchload
    -u {{ ibm_infosvr_user_isadmin }}
    -p {{ ibm_infosvr_upwd_isadmin }}
    -dom {{ ibm_infosvr_hosts.domain | lower }}:{{ ibm_infosvr_ports.console }}
    -command START
    -all
  args:
    executable: /bin/bash
    chdir: "{{ ibm_infosvr_install_location.linux }}/Server/DSEngine"
  when: >
    ('ibm_information_server_engine' in group_names)
    and __ibm_infosvr_features.ises
    and __ibm_infosvr_version == "11.7"
  tags:
    - "sync_and_index"

- name: re-build the ISES indexes
  uri:
    url: "https://{{ ibm_infosvr_hosts.domain }}:{{ ibm_infosvr_ports.console }}\
          /ibm/iis/common-utils/rest/v1/app/reindex?batchSize=25&solrBatchSize=100&upgrade=true&force=true"
    method: GET
    user: "{{ ibm_infosvr_user_isadmin }}"
    password: "{{ ibm_infosvr_upwd_isadmin }}"
    force_basic_auth: yes
    status_code: 200
    validate_certs: no
    timeout: 120
  ignore_errors: yes
  when: ('ibm_information_server_domain' in group_names)
  tags:
    - "sync_and_index"

- import_tasks: setup_vars.yml

- import_tasks: configure/configure-omag.yml
  when: >
    __ibm_infosvr_features.omag
    and __ibm_infosvr_version == "11.7"
    and ('ibm_information_server_ug' in group_names)
