---
- name: Apache_httpd | Check Apache version
  command: apachectl -v
  register: apache_installed_version
  changed_when: false
  failed_when: false

- name: Apache_httpd | Set apache_installed_version fact
  set_fact:
    apache_installed_version: "{{ apache_installed_version }}"

- name: Apache_httpd | Check Brotli version
  command: brotli -V
  register: apache_brotli_installed_version
  changed_when: false
  failed_when: false

- name: Apache_httpd | Set apache_brotli_installed_version fact
  set_fact:
    apache_brotli_installed_version: "{{ apache_brotli_installed_version }}"

- name: Apache_httpd | Check mod_jk version
  command: strings {{ apache_install_dir }}/modules/mod_jk.so
  register: apache_modjk_installed_version
  changed_when: false
  failed_when: false

- name: Apache_httpd | Set apache_modjk_installed_version fact
  set_fact:
    apache_modjk_installed_version: "{{ apache_modjk_installed_version }}"
